server:
  port: 9090

  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  http:
    encoding:
      charset: UTF-8
      enabled: true